#+TITLE: Manifesto
#+AUTHOR: Sahra Roman \& Christian Sangvik


* Interview from Bjarke Ingels, 2015

*Architecture is the art of turning science and fiction in to fact.*
ScienceFiction is not a space opera and it's not a story from the future even
though it often is. *Science Fiction is a Story where the plot is triggered by
some form of innovation.* Typically it's a technological innovation but it can be
cultural, social, political, etc. And it happens in a world, that is exactly like our
world but there is this one thing that has been altered. And the whole story is
the narrative exploration of the potential or the consequences of that idea, of
that change.*

And what we do in architecture is that we always try to see is whenever we get
invited to look at a situation or make a building. We try to analyze how is the
status quo. Has things changed since the last time somebody built a school or
like a workplace and we try to look for potential changes and at some point,
once you find a thing that has already changed but nobody has realized the
potential of it, or it could change but nobody has tried it before, then you get
this like one altered fact just like in science fiction that can then trigger a
whole cascade of consequences /and the designwork becomes the architectural
exploration of the potential of that idea./
