#+TITLE: Ab Ovo
#+SUBTITLE: (work on title)
#+AUTHOR: Sahra Roman \and Christian Sangvik
#+DATE: \today

#+DESCRIPTION:
#+KEYWORDS: Mira,Brandlhuber,HS2017,HS17,TV,Station,StationPlus,Station+

#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [11pt,a4paper,ngerman]

#+LATEX_HEADER: \addtokomafont{disposition}{\rmfamily}

#+LATEX_HEADER_EXTRA:
#+LATEX_COMPILER: pdflatex

  
* Generelle Beschreibung
  
  Die Serie beschäftigt sich mit den Möglichen Welten, in welchen wir
  möglicherweise leben würden, wenn gewisse andere Rahmenbedingungen gegeben
  wären. Die Welten zwischen den einzelnen Seasons müssen und sollen nicht die
  gleichen sein.

  Das Ziel ist, eine konsistente Rahmenbedingung über eine komplette Season zu
  beschreiben und ein möglicher Weg, hierin zu leben und Arbeiten. Innerhalb der
  Season wird eine chronologische Geschichte erzählt. In jeder Episode nehmen
  wir jedoch die Perspektive eines anderen Charakters ein.

  In der ersten Season befinden wir uns in einer möglichen Welt in der
  unmittelbaren Zukunft. Sie hat gegenüber unserer Welt einen Vorsprung von
  ungefähr fünf Jahren.
  
  Die Technik ist einen Schritt weiter gekommen.

* Charaktere

** ETH

*** Gudzilla (ETH Präsident)
    
    Der Präsident der Eidgenössischen Technischen Hochschule in Zürich.

    Er ist ein ambintionierter und seriöser Mensch.

    Sein Interesse gilt sowohl der Lehre, wo er eine sich weiterentwickelnde
    Schule führen will, und somit auch viel Geld in die Forschung und gute
    Dozenten steck, wie auch der Ökonomie, wo er sich den Geldgebern gegenüber
    verpflichtet fühlt, und trotz seiner freigiebigen Ader für die Forschung
    gewisse Projekte nicht unterstützen will und kann.

    Er is der direkte Vorgesetzte von Dr. Brown, wessen Forschung er aus mangel
    an Erfolg beenden will. Nach Dr. Browns Durchbruch wird dieser für ihn
    jedoch zu einem Vorzeigeexemplar der Forschung am Haus.
    
*** Professor Brändi
    
    /Prof. Brändi/ ist ein Urgestein des Lehrkörpers an der Architekturfakultät
    der ETH Zürich.
    
    Er ist zwar innovativ und hat es verstanden seine Architektur an die
    Gegebenheiten der Zeit anzupassen, ist aber seinen alten Methoden treu
    geblieben. Er erfreut sich grosser Beliebtheit bei den Studenten, da er mit
    seiner Bestimmtheit, konstruktiven Kritik aber vor allem seiner
    Menschlichkeit und Nahbarkeit punktet.

    Auch unter seinen Kollegen geniesst er grossen Respekt, sowohl für seine
    Architektur wie auch die Didaktik.

*** Dr. Brown (Programmierer)
    
    /Dr. Brown/ ist ein Programmierer an der ETH. Er ist ausgebildeter aber
    gescheiterter Architekt, und hat sich in seinem Schaffen der Technologie
    zugewendet. Im Rahmen seiner Arbeit hat er den Ansatz des CAD zeichnens
    weiterentwickelt, und an einem Programm namens `Dreamcatcher'
    mitgeschrieben. /Dreamcatcher/ ist ein Programm, welches das Design von
    Architektur um ein vielfaches vereinfachen soll. Mit der Eingabe von
    diversen relevanten Parametern produziert das Programm verschiedene Lösungen
    zur architektonischen Gestaltung. Der Architekt wählt dann aus der Liste der
    Resultate eines aus, welches er dann verfeinert.

    Brown hat diese Automation nie vollends befriedigt. Für seine Forschung hat
    er dieses Programm weiterentwickelt. Auch um sein Scheitern im Beruf
    aufzuwiegen. Unter dem Namen ``Mira'' hat er eine künstliche Intelligenz
    entworfen, welche sich die relevanten Parameter, und auch erheblich mehr,
    zusammensucht und letztendlich selber entscheidet, welches das beste und
    schönste Design ist, so dass das Produkt der fertige Entwurf ist.

    Nach anfänglichen Rückschlägen und der Androhung des ETH Präsidenten
    Gudzilla, seine Mittel zu streichen, war er am Schluss trotz allem
    erfolgreich. Er geniesst seinen neuen Ruhm und stellt voller Stolz seine
    Künstliche Intelligenz, bei jeder sich bietenden Gelegenheit vor. Dies unter
    anderem auch im Rahmen einer grossen öffentlichen Vorlesung an der ETH
    selber.

*** Mira (K.I.)
    
    /Mira/ ist eine künstliche Intelligenz. Sie ist ein Programm, welches von
    Dr. Brown geschrieben wurde, welches den architektonischen Entwurf
    automatisieren kann. Gegenüber einer gewöhnlichen K.I. meistert Mira nicht
    nur logische Entscheidungen sondern auch /intuitive/. Sie hat die
    Fähigkeiten /zu beurteilen/ und die Welt, wie auch ihr eigenes `Denken'
    /reflexiv/ zu betrachten und zu hinterfragen. Im Gegensatz zu anderen
    Erzählungen mit künstlichen Intelligenzen hat Mira jedoch keine empathischen
    Fähigkeiten. Ebenfalls tritt Mira auch nicht physisch in Erscheinung.

    In Verbindung mit dem Benutzer tritt Mira über ein sprachliches Interface,
    wie auch über den visuellen Kanal.
    
    Mira ist keineswegs ein bösartiges Programm welches die Weltherrschaft an
    sich reissen will, sondern nur pragmatisch interessiert, das ihr gegebene
    Problem möglichst effizient zu lösen. Da sie für den Architekturentwurf
    programmiert wurde, beschränkt sich ihr tun hierauf.
    
    Hierin geht sie aber um ein vielfaches weiter als ein Vorgängerprogramm von
    ihr namens `Dreamcatcher'. Sie sucht sich Entwurfsparameter eigenständig
    zusammen und entscheidet nicht nur basierend auf logischen Daten, welcher
    Entwurfsansatz weiter zu entwickeln sei. Ästhetische Vorlieben der
    Gesellschaft und des Kontext fliessen bei ihrem Entwurf ebenso ein, wie die
    Anforderungen des Baurechtes.

    Zu beginn verhält sich /Mira/ wie ein Kind, welches alles lernen und
    erfragen muss. Sie muss sich ihre eigene Wissensdatenbank anfertigen und
    vergisst niemals. Ebenso denkt sie alle Ansätze weiter. Mit wachsendem
    Wissen ist sie dann in der Lage, selber kreative und konstruktive
    Entscheidungen zu treffen.
    
    Prinzipiell macht Mira die Entwicklung eines Menschen durch. Dies jedoch in
    kürzester Zeit, weshalb sie vielmehr die Entwicklung /aller/ Menschen
    durchmacht.
    
    Da sie sich nicht linear entwickeln muss ist sie gleichsam eine einzelne
    Entität, die jedoch wie ein komplettes globales Netzwerk funktioniert.
    
    Limitierungen hat die K.I. jdeoch immernoch. Dies vor allem im
    künstlerischen Aspekt. Auch steht die Frage noch offen, was denn beim
    /Scheitern/ an einem Projekt passiert.

*** Alessia [Ale]
    
    /Alessia/ ist eine Studentin am Lehrstuhl Brändi.
    
    Sie kommt aus gutem Haus, hat in ihrem Leben viel Wohlstand genossen, ist
    aber trozdem nicht zu einem verwöhnten Mädchen geworden. Ihre Eltern sind
    relativ streng in der Erziehung, haben ihr nichts in den Schoss gelegt, und
    sie musste sich immer einsetzen, um ihre Ziele zu erreichen. Deshalb ist sie
    selbstbewusst, mutig und lässt sich nicht schnell unterkriegen. Sie braucht
    eigentlich nur sich selbst um über die Runden zu kommen.

    Sie ist tüchtig und erfolgreich, sowohl im Sozialen, wie auch im Studium.

    Im Studium hat sie sich mit ihren Kommilitonen Jan und Tim
    angefreundet. Obwohl die drei grund verschieden sind haben sie trotzdem eine
    gemeinsame Basis für ein gutes zusammensein gefunden.

*** Tim
    
    /Tim/ ist ebenfalls Student am Lehrstuhl Brändi.

    Er ist der Musterschüler jeder Klasse. Er ist intelligent und versteht
    Zusammenhänge häufig schneller als jeder sonst. Da er sehr hilfsbereit und
    empathisch ist, ist er äusserst beliebt bei den anderen Studenten.
    
    Mit seinem Engagement in der Hochschulpolitik trägt er zum Wohle aller bei.
    
    Jan ist seit langer zeit Tims bester Freund.

*** Jan
    
    /Jan/ war in seinem Leben nicht immer gut gestellt. Er lebt zusammen mit
    seiner alleine erziehenden Mutter in einer kleinen Wohnung.
    
    Er ist sympathisch und zugänglich. Sein Fokus in seinem Leben liegt in
    seinem sozialen Umfeld. Architektur ist für Jan nicht nebensächlich, er ist
    aber nicht besonders gut im Studium. Widerum ist er auch nirgends wirklich
    schlecht. Wenn es um die schulischen Leistungen geht, ist er die Inkarnation
    von /durchschnittlich/.
    
    Er macht sich Probleme, wo keine sind, und vermag es nicht allzu gut sich
    auf das wesentliche zu konzentrieren.

    
*** Studenten
    
    Das Gros der Studenten. Wir fokussieren hier auf die Studenten des
    Lehrstuhles Brändi.

**** Dreigespann
    
     Die drei Studenten Alessia, Tim und Jan stehen in einer Art
     Dreiecksbeziehung, wo Spannungen auf verschiedenen Ebenen bestehen.

     Die drei Protagonisten hier sind in unserer Geschichte für die
     zwischenmenschliche Ebene zuständig. Eine komplexe Liebesgeschichte wird
     angedeutet.

     Die drei könnten grossen Enfluss auf weitere Gestaltung der
     Architekturausbildung haben.
    

** Zürich

*** Stadtpräsidentin Rauch
    
    Muss für Wiederwahl kämpfen, setzt Mira als Wahlkampfmittel ein, da Mira gut
    ankommt bei der Bevölkerung.  Übergibt Amt des Städtebaus an Mira. Oder
    reisst Mira es an sich?
    
*** Amt für Städtebau
    
**** Giovanni (Vater von Ale)
     
     Giovanni ist der Vater von Alessia. Er ist seit langer Zeit glücklich
     verheiratet und wohnt zusammen mit seiner Frau und seinen zwei Kindern,
     Alessia und ihr jüngerer Bruder, in einem grossen Haus in einem gehobenen
     Gebiet der Stadt.
     
     Verliert Job. Zwingt nachher Ale das Studium abzubrechen, obwohl es ihr
     Traumberuf ist.  Kandidiert zum Direktor des Amtes für Städtebau.
     
     Strikt, formalistisch, ambitioniert.
     
     Vermag es Familie und Arbeit zu trennen.  Er ist zwar herzlich, aber hat
     Probleme, Gefühle zu zeigen.

     Vater von zwei Kindern. Alessia ist das Vorzeigekind.  Der jüngere Sohn
     Dino rebelliert zuhause und interessiert sich nicht für Architektur.
     
     Ist glücklich verheiratet, neigt jedoch seit seiner Kandidatur für das Amt
     des Direktors dazu, zu viel Zeit im Büro abzusitzen.
    
*** Architekten
    
    Merken erst spät, dass sie betroffen sind von den Auswirkungen von Mira.
  
*** Medien Zürich
    
    Vielleicht ein Journalist, der Protagonistenrolle einnimmt.

*** Zürcher Bevölkerung
    
    Sind begeistert von Mira, da Mira in kürzester Zeit und ökonomisch optimiert
    wirklich gute Architektur erstellt.

* Season 1 | Mira
  
  Die Geschichte erzählt aus der Perspektive von wechselnden Protagonisten aber
  mit Mira als Hauptfigur.

** Geschichte
   
*** Setup
   
     Dr. Brown hat Erfolg mit der Programmierung der K.I.

*** Plotpoint I
    
    Mira nimmt an Wettbewerb teil und gewinnt. Die Menschen sind begeistert vom
    Design und den vorgeschlagenen Kosten und Bauzeiten.
   
*** Rising Action
    
    Lagerbildung. Zürcher nehmen Mira positiv auf, durch alle Vorteile,
    Architekten kämpfen aber dagegen an, weil sie obsolet werden.

*** Peak
    
    Mira übernimmt Amt für Städtebau. Mit dem läuft Mira auf vieler Hardware,
    was ein Ausschalten quasi unmöglich macht.

*** Falling Action
    
    Mittlerweile hat Mira viele Feinde, da sie nach und nach alle überflüssig
    macht. Jemand versucht Mira auszuschalten. Anschläge werden
    verübt. Studentenbewegungen wehren sich mittlwerweile aktiv gegen Mira.

*** Plotpoint II
    
    Mira Failure
   
    Mira entwickelt die "perfekte" Architektur, kommt ans Ende des
    Lernprozesses. Allerdings sind die Menschen nicht so weit, das Resultat zu
    akzeptieren. Für die beteiligten Menschen fehlt der Prozess. Wir können
    keine Endgültige Lösung akzeptieren, wenn wir nicht verstehen können, wie
    man darauf kommt. Ausserdem brauchen wir zeit, um uns an Neues zu
    gewöhnen. Im Endeffekt ist Mira einfach zu schnell für den Menschen.
    
    Es muss ein prinzipieller Fehler vorliegen, wenn das Endresultat der
    Entwicklung nicht angenommen wird. Wenn das Resultat quasi falsch ist, kann
    die Methode nicht stimmen.
    
    Mira kommt an ihre Grenzen. Irgendwann ist jeder Wettbewerb gelöst, und
    dann?  Infrastrukturelle Engpässe Im Versuch, die Architektur komplett neu
    zu denken, und allen Balast wie auch die Geschichte abzuwerfen, entwickelt
    Mira die "perfekte" Architektur.

*** Resolution
    
    Studium passt sich an neue Gegebenhenheiten an, Menschen lernen, damit
    umzugehen, und eine neue Rolle in der Architektur einzunehmen. Brändi, der
    konservative Professor initiiert Versöhnung mit der Maschine. Botschaft am
    Ende: Alle haben sich damit abgefunden, dass Mira mittlerweile Teil der
    Gesellschaft wird. Man sieht aber, wie Brown Mira 2.0 entwickelt.
    Hoffnungsvolles aber ungewisses Ende.
    
***** Mira geburt

***** Mira nimmt Teil an Wettbewerb

***** Mira gewinnt Wettbewerb

***** Medienrummel um Mira, Positive Reaktion der Zürcher

***** Mira übernimmt Amt für Städtebau

***** Anschläge auf Mira (von feindlichem Lager)

***** Mira Fail

***** Veränderte Einstellung des Departements für Architektur gegenüber Mira

***** Designer arbeiten mit Mira. Aber Brown hat schon Mira 2.0 in Entwicklung
    

** Episoden

*** Episode 1 | Jan
    
    In der ersten Episode steht Jan im Vordergrund.
    
    CAD wird parametrisiert ausgeführt (Dreamcatcher).

    Jan schafft es nicht sofort dir richtigen Parameter einzustellen.

    Kurz vor der Zwischenkritik läuft seine Lizenz zu Dreamcatcher aus,
     
**** Incident

***** Brown
     
      Guzilla sucht Büro von Brown auf, um ihm zu vermitteln, dass seine
      Forschungsgelder gestrichen werden.

***** Jan

      Jans Lizenz für Dreamcatcher läuft kurz vor der Zwischenkritik aus.

**** Plotpoint 1

     Jan findet dubioses Programm namens Mira und installiert es. Es ist noch
     nicht vollständig ausgereift, trägt aber deutlich mehr zum Entwurf bei als
     Dreamcatcher.

**** Midpoint

     Jan brilliert an der Kritik. Gastkritiker sind Juroren des Amtes für
     Städtebau.  Auf der Feier nach der Kritik kommen sich Ale und Jan näher.
     
     Es wird offenkundig, dass Mira gestolen wurde. ETH stellt erfolglose
     Untersuchung an.  (Muss nicht erwähnt werden)

**** Falling action

     Jan verbringt weniger Zeit mit Ale und Tim, da er von Mira begeistert ist,
     und ihren Wissenshunger stillen muss.

     Tim ist eifersüchtig, da er von Jan überflügelt wurden. Er trifft sich mit
     Ale, und sie stellen die Veränderung in Jans verhalten fest. Die zwei
     kommen sich im gemeinsamen Trinken ein wenig näher.
     
     Jans privatleben geht troz seines Erfolges im Studium bergab, da er seine
     Zeit quasi zur gänze Mira widmet. Als er von Ale und Tims nächtlicher
     Eskapade erfährt fühlt er sich übergabgen.

**** Plotpoint 2

     Jan ist ständig Müde.  Wird von Brown überwacht, da er dessen
     Versuchskaninchen ist.
     
   
**** Resolution
     
     Auflösung, dass Brown selber Mira gestolen und verbreitet hat.
     
**** Punkte in Geschichte

***** Lizenz für Dreamcatcher läuft aus / Dr. Brown werden die Mittel gestrichen

***** Runterladen von Mira

***** Jan wird besser im Unterricht, Verbring zeit mit Mira

***** Jan brilliert an Zwischenkritik / Leak wird in Dr. Browns Labor entdeckt

***** Mira verlangt mehr Aufmerksamkeit

***** Tim und Ale kommen sich näher

***** Jan und Tim haben Auseinandersetzung

***** Brown überwacht Jan > Leak war von Brown
     
*** Episode 2 | Giovanni
    
    Mira nimmt an einem Wettbewerb teil und gewinnt diesen.

    Beziehung zur Tochter. Will nur das beste für seine Tochter und erachtet die
    Ausbildung als etwas des wichtigsten.
    
    Wettbewerb von hinter der Kulisse.
    
    Die Jury behandelt den Wettbewerb anonym und findet erst nach der
    Beurteilung heraus, dass Mira eine Küstliche Intelligenz ist. Eine Debatte
    über das weitere Verhalten bricht aus.
    
**** Wettbewerb
     
     Ein Wettbewerb der Stadt wird von Giovanni betreut.  Wettbewerb neigt sich
     dem Ende zu.

**** Incident

**** Plot Point I

**** Rising Action

**** Midpoint

**** Falling Action

**** Plot Point II

**** Resolution

**** Cliffhanger

**** Punkte in Geschichte

***** Beziehung/Situation zu hause + bei Arbeit

***** Vorbereitung Jurierung

***** Diskussion der Jury über Einreichungen

***** Jury kürt Miras Projekt als Sieger

***** Mira ist ein Programm

***** Widerrufung des Siegerprojekts

***** Diskussion der Jury über Mira - Grundsatzentschid

***** Mira darf weitermachen

*** Episode 3 | Dr. Brown

**** Punkte in Geschichte
    
***** Alles läuft nach Plan, Brown beobachtet Jan weiterhin im geheimen

***** Medienrummel um Mira > Wer ist der Erschaffer

***** Brown gibt sich zu erkennen

***** TV interview goes viral

***** Vorlesung > Angriff der Arch Studenten

***** Gudzilla findet heraus, dass Brown Mira gestohlen hat.

***** Einladung nach MIT / internationale Vorträge

***** Brown bekommt gute Angebote aus der Privatwirtschaft zum Weiterentwicklung seiner K.I.

***** Gudzilla erpresst Brown, damit dieser bleibt (Weiss dass Brown geleakt hat)
   
*** Episode 4 | Stadtpräsidentin Rauch
   
**** Punkte in Geschichte

***** Rauch zuhause, schöne Beziehung

***** Release Abstimmung kommt vors Volk (Miras Projekt)

***** Positive Reaktion der Zürcher über Miras Projekt. Finanzpolitik wird besser

***** Rauch wird wiedergewählt

***** Giovanni sucht Gespräch mit Stadtpräsidentin, beklagt sich wegen steuerung der Server. Auch andere Anliegen der Architekten werden vorgetragen.

***** Rauch nimmt Kontakt mit Mira auf

***** Massenentlassung im Amt für Städtebau
      
***** Mira übernimmt Amt für Städtebau
   
*** Episode 5 | Alessia

**** Punkte in Geschichte

***** Alessia ist sehr engagiert für die Architektur. Grosser Traum. Voller Stundenplan und sehr integriert

***** Giovanni aufgebracht zuhause, wütend und verzweifelt. Verliert Job. Regt sich über sich selber auf

***** Giovanni sieht keine Zukunft in der Architektur. Erwartet von Alessia, dass sie das Studium wechselt

***** Innerer Clinch, grenzt sich ab

***** Versöhnung mit Bruder

***** Ale rebelliert

***** Alessia redet mit Tim über Situation gesteht inneren Clinch. Gibt ihm Infos von zu hause.

***** Ale und Tim entscheiden sich Widerstand zu leisten.

***** Jan zeigt Alessia und Tim Mira

*** Episode 6 | Tim

**** Punkte in Geschichte

***** 

*** Episode 7 | Professor Brändi
   
**** Punkte in Geschichte

***** 
   
*** Episode 8 | Gudzilla
   
**** Punkte in Geschichte

***** 

