#+TITLE: Scenario
#+SUBTITLE: Treatment
#+AUTHOR: Sahra Roman \and Christian Sangvik
#+DATE: \today

#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [11pt,a4paper,ngerman]
#+LATEX_HEADER: \usepackage{ngerman}
#+LATEX_HEADER: \addtokomafont{disposition}{\rmfamily}
#+LATEX_COMPILER: pdflatex
  
* Generelle Beschreibung
  
  Die Serie beschäftigt sich mit den Möglichen Welten, in welchen wir
  möglicherweise leben würden, wenn gewisse andere Rahmenbedingungen gegeben
  wären. Die Welten zwischen den einzelnen Seasons sind nicht die gleichen.

  Das Ziel ist, eine konsistente Rahmenbedingung über eine komplette Season zu
  beschreiben und ein möglicher Weg, hierin zu leben und Arbeiten. Innerhalb der
  Season wird eine chronologische Geschichte erzählt. In jeder Episode nehmen
  wir jedoch die Perspektive eines anderen Charakters ein.

  In der ersten Season befinden wir uns in einer möglichen Welt in der
  unmittelbaren Zukunft. Sie hat gegenüber unserer Welt einen Vorsprung von
  ungefähr fünf Jahren.
  
  Die Technik ist einen Schritt weiter gekommen.


* Cast und Rollen

** Lino Gudzilla (ETH Präsident)
    
   Der Präsident der Eidgenössischen Technischen Hochschule in Zürich.

   Er ist ein ambintionierter und seriöser Mensch.

   Sein Interesse gilt sowohl der Lehre, wo er eine sich weiterentwickelnde
   Schule führen will, und somit auch viel Geld in die Forschung und gute
   Dozenten steck, wie auch der Ökonomie, wo er sich den Geldgebern gegenüber
   verpflichtet fühlt, und trotz seiner freigiebigen Ader für die Forschung
   gewisse Projekte nicht unterstützen will und kann.

   Er is der direkte Vorgesetzte von Dr. Brown, wessen Forschung er aus mangel
   an Erfolg beenden will. Nach Dr. Browns Durchbruch wird dieser für ihn
   jedoch zu einem Vorzeigeexemplar der Forschung am Haus.
    
** Professor Arno Brändi
    
   /Prof. Brändi/ ist ein Urgestein des Lehrkörpers an der Architekturfakultät
   der ETH Zürich.
    
   Er ist zwar innovativ und hat es verstanden seine Architektur an die
   Gegebenheiten der Zeit anzupassen, ist aber seinen alten Methoden treu
   geblieben. Er erfreut sich grosser Beliebtheit bei den Studenten, da er mit
   seiner Bestimmtheit, konstruktiven Kritik aber vor allem seiner
   Menschlichkeit und Nahbarkeit punktet.

   Auch unter seinen Kollegen geniesst er grossen Respekt, sowohl für seine
   Architektur wie auch die Didaktik.

** Dr. Stanislav Brown (Programmierer)
    
   /Dr. Brown/ ist ein Programmierer an der ETH. Er ist ausgebildeter aber
   gescheiterter Architekt, und hat sich in seinem Schaffen der Technologie
   zugewendet. Im Rahmen seiner Arbeit hat er den Ansatz des CAD zeichnens
   weiterentwickelt, und an einem Programm namens `Dreamcatcher'
   mitgeschrieben. /Dreamcatcher/ ist ein Programm, welches das Design von
   Architektur um ein vielfaches vereinfachen soll. Mit der Eingabe von
   diversen relevanten Parametern produziert das Programm verschiedene Lösungen
   zur architektonischen Gestaltung. Der Architekt wählt dann aus der Liste der
   Resultate eines aus, welches er dann verfeinert.

   Brown hat diese Automation nie vollends befriedigt. Für seine Forschung hat
   er dieses Programm weiterentwickelt. Auch um sein Scheitern im Beruf
   aufzuwiegen. Unter dem Namen ``Mira'' hat er eine künstliche Intelligenz
   entworfen, welche sich die relevanten Parameter, und auch erheblich mehr,
   zusammensucht und letztendlich selber entscheidet, welches das beste und
   schönste Design ist, so dass das Produkt der fertige Entwurf ist.

   Nach anfänglichen Rückschlägen und der Androhung des ETH Präsidenten
   Gudzilla, seine Mittel zu streichen, war er am Schluss trotz allem
   erfolgreich. Er geniesst seinen neuen Ruhm und stellt voller Stolz seine
   Künstliche Intelligenz, bei jeder sich bietenden Gelegenheit vor. Dies unter
   anderem auch im Rahmen einer grossen öffentlichen Vorlesung an der ETH
   selber.

** Mira (K.I.)
   
   Für mira wird nur eine Stimme gebraucht, sie manifestiert sich nicht
   physisch. 
    
   /Mira/ ist eine künstliche Intelligenz. Sie ist ein Programm, welches von
   Dr. Brown geschrieben wurde, welches den architektonischen Entwurf
   automatisieren kann. Gegenüber einer gewöhnlichen K.I. meistert Mira nicht
   nur logische Entscheidungen sondern auch /intuitive/. Sie hat die
   Fähigkeiten /zu beurteilen/ und die Welt, wie auch ihr eigenes `Denken'
   /reflexiv/ zu betrachten und zu hinterfragen. Im Gegensatz zu anderen
   Erzählungen mit künstlichen Intelligenzen hat Mira jedoch keine empathischen
   Fähigkeiten. Ebenfalls tritt Mira auch nicht physisch in Erscheinung.

   In Verbindung mit dem Benutzer tritt Mira über ein sprachliches Interface,
   wie auch über den visuellen Kanal.
    
   Mira ist keineswegs ein bösartiges Programm welches die Weltherrschaft an
   sich reissen will, sondern nur pragmatisch interessiert, das ihr gegebene
   Problem möglichst effizient zu lösen. Da sie für den Architekturentwurf
   programmiert wurde, beschränkt sich ihr tun hierauf.
    
   Hierin geht sie aber um ein vielfaches weiter als ein Vorgängerprogramm von
   ihr namens `Dreamcatcher'. Sie sucht sich Entwurfsparameter eigenständig
   zusammen und entscheidet nicht nur basierend auf logischen Daten, welcher
   Entwurfsansatz weiter zu entwickeln sei. Ästhetische Vorlieben der
   Gesellschaft und des Kontext fliessen bei ihrem Entwurf ebenso ein, wie die
   Anforderungen des Baurechtes.

   Zu beginn verhält sich /Mira/ wie ein Kind, welches alles lernen und
   erfragen muss. Sie muss sich ihre eigene Wissensdatenbank anfertigen und
   vergisst niemals. Ebenso denkt sie alle Ansätze weiter. Mit wachsendem
   Wissen ist sie dann in der Lage, selber kreative und konstruktive
   Entscheidungen zu treffen.
    
   Prinzipiell macht Mira die Entwicklung eines Menschen durch. Dies jedoch in
   kürzester Zeit, weshalb sie vielmehr die Entwicklung /aller/ Menschen
   durchmacht.
    
   Da sie sich nicht linear entwickeln muss ist sie gleichsam eine einzelne
   Entität, die jedoch wie ein komplettes globales Netzwerk funktioniert.
    
   Limitierungen hat die K.I. jdeoch immernoch. Dies vor allem im
   künstlerischen Aspekt. Auch steht die Frage noch offen, was denn beim
   /Scheitern/ an einem Projekt passiert.

** Alessia [Ale] Benini
    
   /Alessia/ ist eine Studentin am Lehrstuhl Brändi.
    
   Sie kommt aus gutem Haus, hat in ihrem Leben viel Wohlstand genossen, ist
   aber trozdem nicht zu einem verwöhnten Mädchen geworden. Ihre Eltern sind
   relativ streng in der Erziehung, haben ihr nichts in den Schoss gelegt, und
   sie musste sich immer einsetzen, um ihre Ziele zu erreichen. Deshalb ist sie
   selbstbewusst, mutig und lässt sich nicht schnell unterkriegen. Sie braucht
   eigentlich nur sich selbst um über die Runden zu kommen.

   Sie ist tüchtig und erfolgreich, sowohl im Sozialen, wie auch im Studium.

   Im Studium hat sie sich mit ihren Kommilitonen Jan und Tim
   angefreundet. Obwohl die drei grund verschieden sind haben sie trotzdem eine
   gemeinsame Basis für ein gutes zusammensein gefunden.

** Tim Bergmann
    
   /Tim/ ist ebenfalls Student am Lehrstuhl Brändi.

   Er ist der Musterschüler jeder Klasse. Er ist intelligent und versteht
   Zusammenhänge häufig schneller als jeder sonst. Da er sehr hilfsbereit und
   empathisch ist, ist er äusserst beliebt bei den anderen Studenten.
    
   Mit seinem Engagement in der Hochschulpolitik trägt er zum Wohle aller bei.
    
   Jan ist seit langer zeit Tims bester Freund.

** Jan Aebersold
    
   /Jan/ war in seinem Leben nicht immer gut gestellt. Er lebt zusammen mit
   seiner alleine erziehenden Mutter in einer kleinen Wohnung.
    
   Er ist sympathisch und zugänglich. Sein Fokus in seinem Leben liegt in
   seinem sozialen Umfeld. Architektur ist für Jan nicht nebensächlich, er ist
   aber nicht besonders gut im Studium. Widerum ist er auch nirgends wirklich
   schlecht. Wenn es um die schulischen Leistungen geht, ist er die Inkarnation
   von /durchschnittlich/.
    
   Er macht sich Probleme, wo keine sind, und vermag es nicht allzu gut sich
   auf das wesentliche zu konzentrieren.
    
** Studenten
    
   Das Gros der Studenten. Wir fokussieren hier auf die Studenten des
   Lehrstuhles Brändi. Es werden daher ca. 10 bis 20 Einzelne Studenten
   benötigt. 

*** Dreigespann
    
    Die drei Studenten Alessia, Tim und Jan stehen in einer Art
    Dreiecksbeziehung, wo Spannungen auf verschiedenen Ebenen bestehen.

    Die drei Protagonisten hier sind in unserer Geschichte für die
    zwischenmenschliche Ebene zuständig. Eine komplexe Liebesgeschichte wird
    angedeutet.

    Die drei könnten grossen Enfluss auf weitere Gestaltung der
    Architekturausbildung haben.

** Stadtpräsidentin Corinne Rauch
    
   Muss für Wiederwahl kämpfen, setzt Mira als Wahlkampfmittel ein, da Mira gut
   ankommt bei der Bevölkerung.  Übergibt Amt des Städtebaus an Mira. Oder
   reisst Mira es an sich?
    
** Giovanni Benini (Vater von Ale)
     
   Giovanni ist der Vater von Alessia. Er ist seit langer Zeit glücklich
   verheiratet und wohnt zusammen mit seiner Frau und seinen zwei Kindern,
   Alessia und ihr jüngerer Bruder, in einem grossen Haus in einem gehobenen
   Gebiet der Stadt.
     
   Verliert Job. Zwingt nachher Ale das Studium abzubrechen, obwohl es ihr
   Traumberuf ist.  Kandidiert zum Direktor des Amtes für Städtebau.
     
   Strikt, formalistisch, ambitioniert.
     
   Vermag es Familie und Arbeit zu trennen.  Er ist zwar herzlich, aber hat
   Probleme, Gefühle zu zeigen.

   Vater von zwei Kindern. Alessia ist das Vorzeigekind.  Der jüngere Sohn
   Dino rebelliert zuhause und interessiert sich nicht für Architektur.
     
   Ist glücklich verheiratet, neigt jedoch seit seiner Kandidatur für das Amt
   des Direktors dazu, zu viel Zeit im Büro abzusitzen.
    
** Architekten
    
   Eine kleine Gruppe von Architekten.
  
** Medien Zürich
    
   Einige Journalisten, die bei Pressekonferenzen dabei sind und ein
   Fernsehteam.

** Zürcher Bevölkerung
    
   Eine Gruppe Zürcher Stadtbewohner


* Season 1 | Mira
  
  Die Geschichte erzählt aus der Perspektive von wechselnden Protagonisten aber
  mit Mira als Hauptfigur.

** Geschichte
   
*** Setup
   
     Dr. Brown hat Erfolg mit der Programmierung der K.I.

*** Plotpoint I
    
    Mira nimmt an Wettbewerb teil und gewinnt. Die Menschen sind begeistert vom
    Design und den vorgeschlagenen Kosten und Bauzeiten.
   
*** Rising Action
    
    Lagerbildung. Zürcher nehmen Mira positiv auf, durch alle Vorteile,
    Architekten kämpfen aber dagegen an, weil sie obsolet werden.

*** Peak
    
    Mira übernimmt Amt für Städtebau. Mit dem läuft Mira auf vieler Hardware,
    was ein Ausschalten quasi unmöglich macht.

*** Falling Action
    
    Mittlerweile hat Mira viele Feinde, da sie nach und nach alle überflüssig
    macht. Jemand versucht Mira auszuschalten. Anschläge werden
    verübt. Studentenbewegungen wehren sich mittlwerweile aktiv gegen Mira.

*** Plotpoint II
    
    Mira Failure
   
    Mira entwickelt die "perfekte" Architektur, kommt ans Ende des
    Lernprozesses. Allerdings sind die Menschen nicht so weit, das Resultat zu
    akzeptieren. Für die beteiligten Menschen fehlt der Prozess. Wir können
    keine Endgültige Lösung akzeptieren, wenn wir nicht verstehen können, wie
    man darauf kommt. Ausserdem brauchen wir zeit, um uns an Neues zu
    gewöhnen. Im Endeffekt ist Mira einfach zu schnell für den Menschen.
    
    Es muss ein prinzipieller Fehler vorliegen, wenn das Endresultat der
    Entwicklung nicht angenommen wird. Wenn das Resultat quasi falsch ist, kann
    die Methode nicht stimmen.
    
    Mira kommt an ihre Grenzen. Irgendwann ist jeder Wettbewerb gelöst, und
    dann?  Infrastrukturelle Engpässe Im Versuch, die Architektur komplett neu
    zu denken, und allen Balast wie auch die Geschichte abzuwerfen, entwickelt
    Mira die "perfekte" Architektur.

*** Resolution
    
    Studium passt sich an neue Gegebenhenheiten an, Menschen lernen, damit
    umzugehen, und eine neue Rolle in der Architektur einzunehmen. Brändi, der
    konservative Professor initiiert Versöhnung mit der Maschine. Botschaft am
    Ende: Alle haben sich damit abgefunden, dass Mira mittlerweile Teil der
    Gesellschaft wird. Man sieht aber, wie Brown Mira 2.0 entwickelt.
    Hoffnungsvolles aber ungewisses Ende.
    
** Geschichte
   
   Die erste Season wird in acht Episoden erzählt. Jede aus der Sicht eines
   anderen Protagonisten.

   Es geht um die Geschichte der Architekten, Architekturstudenten und die Rolle
   der Technik in der Gesellschaft.
   
   Die Geschichte spielt in der nahen Zukunft, circa fünf Jahre von uns
   entfernt. Die Gegeben- und Gepflogenheiten in der Gesellschaft sind den
   unseren weitestgehend ähnlich, nur hat sich das Handwerk der Architekten
   einigermassen geändert.

   Die Architekten und Architekturstudenten brauchen nicht mehr den ganzen
   Entwurf von Hand zu machen, oder zumindest nicht mehr von Hand
   einzugeben. Mit einem Programm namens /Dreamcatcher/ ist es möglich,
   Parameter eines Projektes zu beschreiben, anhand welcher der Computer
   selbstständig Designs erarbeitet. Diese werden dann von den Architekten
   eingesehen und beurteilt. Vielversprechende Ansätze werden dann manuell
   weiterentwickelt.

   Das Studium der Architektur ist aber zum Zeitpunkt der Geschichte prinzipiell
   immer noch das selbe, welches wir gewohnt sind. Der Hauptunterschied liegt
   lediglich darin, dass wir weniger Zeit darauf verwenden, die Gedanken in
   Pläne zu übersetzen, da dieser Prozess mittels Software weitgehend
   automatisiert wurde.
   
   Forschung im Bereich der Künstlichen Intelligenz und Softwareautomation
   werden an der ETH Zürich gross geschrieben.

   Ein Entwickler an der ETH, /Dr. Brown/, der seines Zeichens auch ausgebildeter
   Architekt ist, es jedoch nie richtig geschafft hat in der Welt der
   Architekten Fuss zu fassen, hat sich der Automation des Entwurfsprozesses
   verschrieben. Er hat bereits an Dreamcatcher mitgeschrieben, und ist in
   seinem Forschungsprojekt nun damit beschäftigt, die Software grundlegend
   weiter zu entwickeln und sie mit den Ansätzen der Künstlichen Intelligenz zu
   paaren. So dass am Schluss der Computer nicht eine Auswahlsendung an
   verschiedenen Entwurfsgrundlagen basierend auf der logischen Interpretation
   relevanter Parameter entsteht, sondern aus komplett eigenem Schaffen des
   Computers der fertige Entwurf resultieren soll. Unter dem Codenamen /Mira/
   hat er also eine Künstliche Intelligenz für die Architektur geschrieben.

   /Miras/ Handlungsfeld ist ausschliesslich an die Architektur gebunden. Sie
   soll keine Künstliche intelligenz werden, welche allgemeine Probleme lösen
   soll, diejenigen der Architektur aber im Detail.

   /Mira/ wird, nachdem der Präsident der ETH, /Gudzilla/, die Mittel der nicht
   von grossen Erfolgen gekürten Forschung von /Dr. Brown/ streichen will, aus
   /Dr. Browns/ Labor gestohlen. Interne Ermittlungen wegen dieses Diebstahles
   werden eingeleitet, versiegen jedoch bald im Nichts.

   In einem öffentlichen Architekturwettbewerb der Stadt Zürich wird später ein
   Beitrag abgegeben, der die anderen um ein vielfaches überflügelt und
   gewinnt. Es stellt sich heraus, dass dies der Beitrag von /Mira/ ist. Eine
   Grundsatzdebatte über das Paradigma einer künstlichen Intelligenz an einem
   Wettbewerb und deren Zulassung wird angebrochen.

   Die Jury der Stadt, unter der Leitung von /Giovanni/, der Anwärter auf das
   frei werdende Amt des Direktors für Städtebau der Stadt Zürich ist, ringt
   sich unter Skepsis und Begeisterung dazu durch, das Projekt zu zu lassen, und
   die Künstliche Intelligenz mit der weiteren Ausführung zu beauftragen.
   
   Als der Erfolg der K.I. publik wird, wird auch deren erschaffer, /Dr. Brown/
   von den Medien heimgesucht. Er geniesst seine neu erlangte Berühmtheit und
   stellt sein Werk gerne und umfassend vor.

   Nach diesem Durchbruch stellt sich /Gudzilla/ vollumfänglich hinter /Brown/
   und verwendet diesen als Vorzeigebeispiel der Forschung an der ETH.

   Die Zürcher sind der Neuerung zum grössten Teil extrem positiv
   gegenüber. Durch /Mira/ und ihre effizienten Ansätze können die Kosten für
   Planung und Erstellung eines Gebäudes extrem gesenkt werden.

    
*** Mira geburt

*** Mira nimmt Teil an Wettbewerb

*** Mira gewinnt Wettbewerb

*** Medienrummel um Mira, Positive Reaktion der Zürcher

*** Mira übernimmt Amt für Städtebau

*** Anschläge auf Mira (von feindlichem Lager)

*** Mira Fail

*** Veränderte Einstellung des Departements für Architektur gegenüber Mira

*** Designer arbeiten mit Mira. Aber Brown hat schon Mira 2.0 in Entwicklung

*** Resolution
    

* Episoden

** Episode 1 | Genesis
    
   Die erste Episode wird aus der Perspektive von /Jan Aebersold/ erzählt.
    
   Jan wacht eines dienstagmorgens an seinem Schreibtisch auf. Er hat versucht
   die Nacht durch zu arbeiten, ist dabei aber eingeschlafen. Der Grund für
   seinen Eifer ist die kommende Kritik am Mittwoch Vormittag.

   Jan ist mit seinem Projekt noch lange nicht so weit, dass er etwas zu
   präsentieren oder besprechen hätte. Er schafft es einfach nicht die für
   dieses Projekt notwendigen Parameter richtig einzustellen, so dass sich ihm
   ein stimmiges Resultat offenbaren würde.

   Daher hat Jan sich mit seinem besten Freund Tim verabredet. Tim soll Jan
   helfen einen Ansatz zu finden, damit dieser seinen Entwurf weiterentwickeln
   kann. Die Zeit dafür hat Tim, da er seinen eigenen Entwurf immer schon Tage
   vor der Abgabe fertig hat. Er ist von seiner Arbeitsmoral her das pure
   Gegenteil von Jan.

   Hastig wirft Jan alle Sachen, die er für den Tag braucht in seinen Rucksack
   und macht sich auf den Weg an die ETH. Da er für seine Verabredung mit Tim
   späht dran ist, warted dieser bereits auf Jan.

   In der Koje versuchen die beiden gemeinsam für Jan einen Ansatz zu
   generieren, den er dann weiter verarbeiten kann. Leider kann sich Jan in der
   Anwesenheit von Alessia, einer Komilitonin sehr leicht ablenken.
    
   Parallel dazu sehen wir die Geschichte von Dr. Brown. Brown ist
   Softwareentwickler an der ETH und hat im Rahmen seiner Forschung eine
   Künstliche Intelligenz entwickelt, welche jedoch noch nicht ganz fertig
   ist. An diesem Morgen hat Brown ein Treffen mit dem Präsidenten der ETH,
   Lino Gudzilla. Gudzilla erklärt Brown, dass er seine Forschung aus Knappheit
   an Forschungsgeldern und mangels Erfolgen von Brown nicht mehr finanzieren
   wird, und stellt Brown als wissenschaftlichen Mitarbeiter frei. So bleibt
   Brown nur noch seine Stelle an der ETH, wo er als Helpdeskmitarbeiter für
   Computerprobleme den Studenten mit ihren technischen Schwierigkeiten zur
   Setie steht.

   Alle Versuche Gudzilla zu überreden, ihm einen Aufschub zu gewähren schlagen
   fehl.

   Unterdessen muss sich Jan zu allem Überfluss noch mit eben solchen
   technischen Schwierigkeiten herumschlagen. Sein Parameterdesign-Programm
   `Dreamfetcher' stürzt ständig ab. Auch Tim und Alessia, die sehr gut mit
   Computern umgehen kann, können ihm nicht helfen, weshalb er sich gezwungen
   fühlt, den Helpdesk aufzusuchen.

   Brown am Helpdesk sieht im alten Computer Jans die perfekte Gelegenheit
   seine noch nicht fertige K.I. auszuprobieren, um letztendlich mit
   offensichtlichen Erfolgen trotzdem wieder als wissenschaftlicher Mitarbeiter
   eingestellt zu werden. Er erzählt Jan also, dass er das Problem bis zum
   Abend beheben werde. Jan kommt in eine riesige Not, da er so seine Abgabe
   niemals schaffen wird. Resigniert stimmt er aber dennoch zu, da dies die
   letzte Chance auf Erfolg ist.

   Brown installiert die K.I. namens `Mira' auf Jans Computer, und meldet sich
   bei ihm, dass er seinen Computer abhohlen kann. Er macht Jan glauben, er
   habe lediglich eine neuere Version von Dreamfetcher installiert, die jedoch
   viel mächtiger sei.

   Jan probiert zuhause noch das schlimmste zu vermeiden, und ist überrascht,
   wie eigenständig das Programm funktioniert. Mittels Sprachsteuerung ung der
   Eigeninitiative der K.I. gelingt letztendlich der Vollständige Entwurf
   seiner Abgabe. Noch dazu ist sie in diesem Fall nicht wie sonst besonders
   durchschnittlich sondern überragend.

   Seine Kritik läuft äusserst gut, und alle sind überrascht. In der Jury
   sitzen neben Prof. Brändi noch Giovanni Benini vom Amt für Städtebau und
   eine andere etablierte Architektin. Abends als die anderen Studenten ihren
   kleinen Erfolg begiessen wollen, meldet sich Jan, der sonst für solche Dinge
   stets an vorderster Front steht ab. Mira verlangt in ihrer Lernphase viel
   Aufmerksamkeit und beansprucht so viel von Jans Zeit.

   An diesem Abend kommen sich Tim und Alessia näher. Jan fällt am nächsten Tag
   sofort auf, dass etwas anders ist. Jan und Tim haben eine
   Auseinandersetzung, wo es um die Eifersucht gegenüber des jeweils anderen geht.
    
   Ohne auf eine richtig gute Lösung gekommen zu sein gehen die beiden
   auseinander. Zuhause versucht Mira wieder von Jans Wissen zu profitieren. Er
   ist aber nicht in der Stimmung und klappt den Laptop zu.

   Auflösend sieht man am Schluss Brown hinter seinem Monitor sitzen, wo die
   Pläne angezeigt werden, welche Jan tags zuvor präsentiert hat.
    
** Episode 2 | Giovanni
    
   Die zweite Episode wird aus der Perspektive von /Giovanni Benini/ erzählt.
    
   Man sieht Giovanni zuhause. Seine Tochter Alessia, sein Sohn Luca und seine
   Frau Laura leben alle gemeinsam im Hause. Die Verhältnisse zu Hause sind
   grösstenteils harmonisch. Nur zwischen Alessia und Luca gibt es hin und wieder
   Rankereien und Rivalitäten. Dies, weil die elterliche Erziehung streng ist,
   und von beiden Leistungen erwartet werden. Giovanni hält die Ausbildung für
   etwas des wichtigsten des Lebens.

   Da Alessia ein Studium in Angriff genommen hat, und dort auch immer gute
   Leistungen erzielt, wird sie oft als Vorbild für Luca vorgehalten, was
   alleine schon diese Rivalität mitbeeinflusst.

   Nach der morgendlichen Routine begibt sich Giovanni zur Arbeit. Am
   Arbeitsplatz spürt man auch die freundliche Art unter den Mitarbeitern, denn
   Giovanni hält nicht viel davon unmenschlich zu sein. Allerdings schwingt
   auch immer Respekt und eine stilvolle, untergiebige Art im Umgang seiner
   Kollegen zu ihm mit. Er nimmt seine Pflichten als Abteilungsleiter ernst,
   und kümmert sich stets speditiv und rasch um alles was ansteht, denn er
   aspiriert für das frei werdende Amt des Direktors des Stadtbauamtes in
   Zürich. Diesbezüglich werden ihm gute Chancen beigemessen.
    
   Aktuell soll die Jurierung des erst jüngst abgehaltenen anonymen
   Wettbewerbes vorbereitet werden. Man sieht die Jurymitglieder und andere
   Kollegen des Amts für Städtebau gemeinsam über die diversen Einreichungen
   diskutieren.
    
   Im Verlaufe der Jurierung stellt sich ein Projekt immer mehr in den
   Vordergrund. Dieses Projekt ist herausragend, und erfüllt als einziges im
   ganzen Teilnehmerfeld alle Bedingungen. Ausserdem spricht die geforderte
   Abschätzung der Kosten für den Bau des Projektes eine ganz andere Sprache
   als die anderen Beiträge. Nur gut die hälfte der Baukosten des
   zweitgünstigsten soll das Projekt kosten. Dies macht die Jury natürlich
   vorerst skeptisch, aber nach mehrmaligem überprüfen scheinen die Zahlen
   plausibel.

   Die Jury kürt folglich logisch das Projekt zum Sieger der Auslobung. Als
   Giovanni nun nachsieht von wem der Beitrag stammt, staunt er nicht schlecht,
   dass er über das Büro `Mira' noch nie etwas gehört hat. Nach kurzen
   nachforschungen kommt Giovanni aber auf den richtigen Autor. Der Beitrag
   wurde von einer Maschine eingereicht.
    
   Als dies bekannt wird, werden alle Schritte eingeleitet, den Wettbewerbssieg
   zu widerrufen.

   Bei einer ausserordentlichen Sitzung beraten sich die Architekten, wie nun
   zu verfahren sei. Es entbrandet eine Grundsatzdiskussion über die Maschine
   und deren Rolle bei Wettbewerben und im Gewerbe generell. Sollen künftig
   beiträge von Programmen berücksichtigt werden?

   In der Diskussion gibt es viel dafür und dawider. Gute Argumente aus beiden
   Lagern werden angeführt. Letztendlich ringen sich die Architekten unter dem
   Urteil von Giovanni durch, dem ganzen einen Versuch zu gestatten. Mira soll
   unter Beweis stellen, wie sie ihre versprochen tiefen Kosten einhalten kann,
   und soll den Wettbewerb für die Ausführung ausarbeiten.

** Episode 3 | Dr. Brown
    
   Die dritte Episode wird aus der Perspektive von /Dr. Stanislav Brown/ erzählt.

   Zu Beginn sieht man Dr. Brown, wie er die Fortschritte von Mira, und damit
   auch Jan überwacht. Brown scheint zufrieden mit den Fortschritten, die sein
   Programm während der letzten Stunden gemacht hat. Sein ausgeklügeltes
   Lernmodul scheint gut zu funktionieren, und auf seine
   Entscheidungsalgorithmen ist er stolz.

   In den Medien ist ein plötzliches, riesiges Interesse an der künstlichen
   Intelligenz erwacht. Ab dem Zeitpunkt wo klar wurde, dass eine K.I. einen
   Architekturwettbewerb gewonnen hat wollten alle über die Sensation
   berichten. Die Umstände, dass die K.I. keinen Autor hat, der sich zu ihr
   bekennt macht die ganze Geschichte noch spannender und sichert Quoten in den
   Nachrichten wie zu Prime-Time-Zeiten.

   Alle Spuren deuten Darauf hin, dass die K.I. aus einem Labor der ETH
   stammt. Es wird offenkundig, dass das Programm /Mira/ aus einem Labor der
   Robotik und Informatik des D-ARCH stammt, wo es scheinbar zuvor entwendet
   wurde. Sicherheitsdebatten kommen auf, aber nichts vermag die Sensation zu
   überbieten, welche die K.I. vollbracht hat.

   Mit steigendem Stolz gibt sich Dr. Brown nach einiger Zeit endlich als Autor
   von Mira zu erkennen, verurteilt öffentlich den Diebstahl, hebt aber vor
   allem die Errungenschaften und Vorzüge von Mira hervor. Die Berichterstattung
   geht um die Welt und sorgt überal für Sensation. Natürlich gibt es immer
   schon zu Beginn von etwas neuem Skeptiker, aber die Grundstimmung ist doch
   sehr euphorisch.
   
   Brown wird vielerorts eingeladen Mira vorzustellen und gemeinsam mit
   prominenten und weniger prominenten zu diskutieren. Sei dies im Fernsehen
   oder auch an Vorträgen und Schulen. Die ETH kann in diesem Trend natürlich
   nicht hinten anstehen und veranstaltet eine Podiumsdiskussion.

   Unter aller positiver Reaktion kann man hier im Hase aber schon eine grössere
   Dichte an skeptischer Stimmen erkennen. Sie sind mira nicht generell negativ
   entgegengestellt, hinterfragen sie jedoch mehr, als sie nur auf einen Sockel
   der Errungenschaft zu stellen. Einige Architekturstudenten, darunter auch Tim
   stellen ungemütliche Fragen, so dass Brown am Ende froh ist, dass die
   Veranstaltung vorüber ist.

   Unterdessen erfährt Gudzilla im Rahmen der internen Ermittlungen zum
   Diebstahl von Mira aus dem Forschungsumfeld, dass Brown sie gestohlen hat. Er
   möchte ihn aus taktischen Gründen nicht jetzt schon blossstellen, da der
   Rummel viel positives Momentum in die Forschungskassen der ETH gebracht hat,
   welches er nicht verspielen will. Ausserdem kann die ETH noch etwas mehr
   positive Engramme in den Köpfen der Menschen brauchen. So behält Gudzilla
   diese Erkenntnis vorerst für sich.

   Brown wird auch an das MIT eingeladen, und bekommt dort auch schon im Voraus
   ein angebot für die Forschung. Die Amerikaner, die der Entwicklung wesentlich
   weniger skeptisch gegenüberstehen, als die Europäer, bejubeln Brown im
   grossen Stil. Am Ende seiner Referatreihe kommen Vertreter von riesigen,
   äusserst reichen Konzernen der digitalen Privatwirtschaft auf Brown zu, und
   versuchen sich gegenseitig auszustechen und ihn für ihr jeweils eigenes
   Unternehmen zur Weiterentwicklung von Mira zu gewinnen.

   Als Brown vor hat der ETH nun den Rücken zu kehren und zu kündigen, um eines
   der vielen Angebote anzunehmen, wird er von Gudzilla aber erpresst und zum
   bleiben gezwungen. Er kann es sich schliesslich nicht leisten, dass sein
   Diebstahl publik wird. Er wird zu einem etwas gekürzten gehalt wieder als
   wissenschaftlicher Mitarbeiter eingestellt.

** Episode 4 | Stadtpräsidentin Schmauch

   Die vierte Episode wird aus der Perspektive der Zürcher /Stadtpräsidentin
   Corinne Schmauch/ erzählt.
   
   Man sieht, wie die tüchtige Präsidentin Schmauch aus dem geschäftigen Alltag
   mit vielen Telefonaten und Terminen nach Hause kommt. Mit dem übertreten der
   Türschwelle wird sie gleichsam ein anderer Mensch. Im Privatleben mit ihrem
   Mann zeigt sie eine unglaublich Menschliche Seite, die mit ihrem harten
   Auftreten im Geschäftsalltag nichts gemeinsam hat. Liebevoll essen die beiden
   und verbringen einen schönen, entspannten Abend.

   Am nächsten Morgen steht schon wieder Wahlkampf an. Schmauch will im Amt
   bleiben, und muss sich so die Gunst der Bevölkerung ständig neu
   verdienen. Die Abstimmung über die Überbauung war im Vorfeld als Routine
   eingeplant gewesen. Da nun aber ein riesiger Rummel um das Siegerprojekt und
   den Umstand, dass dieses nicht aus der Hand eines Architekten oder Büros
   stammt sondern aus dem Hauptspeicher eines Programmes mit künstlicher
   Intelligenz ist von beiläufiger Routinehandlung nichts zu spüren. Schmauch
   muss eben in solchen Situationen mit feinem Fingerspitzengefühl punkten, wenn
   sie ihr Amt auch in Zukunft innehaben will.

   Zu ihrer Überraschung scheint die Reaktion auf das Projekt durchwegs
   positiv. Die Menschen der Stadt scheinen begeistert von der Effizienz und den
   Möglichkeiten kosten einzusparen. So kann mit dem gleichen Budget viel mehr
   erreicht werden. Schmauch, die diese Stimmung sehr schnell wahrnimmt, will
   sich dieses Momentum zu Nutzen machen, und schwimmt mit der Welle der
   Euphorie mit.

   So gestärkt gewinnt sie die Wiederwahl mit für Wahlverhältnisse beachtlichem
   Vorsprung. Es wird klar, dass sie bereits in der Vergangenheit vieles richtig
   gemacht hat, sie sich aber durchaus versteht aus aktuellem Kapital zu
   schlagen.

   Nach einer Feier für ihre Wiederwahl im kleinen Kreise ihrer Freunde und
   Familie wird sie am nächsten Tag aber wieder gefordert. Der Stellvertretende
   Direktor des Amtes für Städtebau sucht sie ausserordentlich zu einem
   dringlichen Gespräch auf. Giovanni Benini beklagt sich bei ihr, dass den
   Mitarbeitern im Stadtbauamt die Hände gebunden sind, da sie kaum etwas machen
   können und auf wichtige Pläne und die Serverstruktur nicht zugreiffen
   können. Mira hat offenbar grosse Teile der Administration in ihren eigenen
   Bereich übertragen und regelt diese nun eigenständig. Auch überbringt
   Giovanni die Mitteilung, dass sich viele Architekten der Stadt bei ihm
   darüber beschwert haben, dass sie kaum zu neuen Aufträgen kommen und sogar
   bereits bestehende Aufträge abgezogen werden aus Gründen der
   Finanzoptimierung der Bauherren.
   
   Schmauch gesteht ein, dass sie zu wenig im Bild ist, sie ist aber gewillt der
   Sache auf den Grund zu gehen und nimmt Kontakt mit Mira auf. In ihrer
   gemeinsamen Unterhaltung zeigt Mira der Präsidentin auf, wo sie bisher
   Optimierungen vorgenommen hat, und legt eindrücklich dar, wie viel Gelder sie
   so bereits einsparen konnte, ohne jemals auf Qualität zu verzichten. Im
   Gegenteil, ihre Projekte scheinen durchdachter und ergiebiger zu sein für die
   Benutzung der Menschen und punkten mit passenden formalen Ansätzen für das
   jeweilige Quartier, wo sie gedacht sind. Es fällt Schmauch schwer, von all
   diesen Vorteilen abzulassen, und so gewährt sie Mira ihr Handeln
   fortzusetzen.

   Eine Welle der Empörung bricht über Schmauch zusammen, als öffentlich wird,
   dass es im Amt für Städtebau Massenentlassungen geben soll. Die Posten die
   nicht unbedingt gebraucht würden, sollen gestrichen werden. So zeigt sich
   nach und nach, dass Mira die Kontrolle über das Amt für Städtebau nun
   vollständig an sich gerissen hat.
   
** Episode 5 | Alessia
   
   Die fünfte Episode wird aus der Perspektive von /Alessia Benini/ erzählt.
   
   Zu Beginn sieht man, wie Alessia Feuer und Flamme für ihre Rolle als
   angehende Architektin ist. Sie ist im Studium äusserst engagiert und auch bei
   allen Komillitonen beliebt. Sie scheut sich nicht auch mal für das Wohle
   aller mehr zu machen, sondern gieniesst insgeheim jeden Moment, in dem sie
   ihren grossen Traum vom Architekt-Sein ausleben kann. Ihr Stundenplan ist so
   voll wie keiner der anderen. Nach einem intensiven Tag geht sie erfüllt nach
   Hause.

   Zu Hause aber hängt der Haussegen schief. Giovanni ist sehr aufgebracht und
   wütend. Zudem mischt sich eine grosse Verzweiflung in das Gefühlschaos,
   welches man klar wahrnehmen kann. Giovanni hat im Rahmen der Rationalisierung
   des Amtes für Städtebau seine Anstellung verloren. Dies kommt besonders
   überraschend, da ihn insgeheim alle schon als den nächsten Direktor für das
   Amt gesehen haben.

   Am schlimmsten für Giovanni ist es jedoch, dass er das Gefühl hat, er müsse
   sich selbst die Schuld für die jetzige Situation geben, da er ja massgeblich
   daran beteiligt war, dass die Pläne der künstlichen Intelligenz am Wettbewerb
   überhaupt zugelassen wurden. Nun scheint für ihn alles so auswegslos. Seine
   Welt droht auseinander zu brechen, und wird nur durch das starke Netz der
   Familie gehalten, auch wenn diese Situation für alle eine immense Belastung
   darstellt.

   Giovanni sieht offen gestanden keine Zukunft mehr für irgendjemanden in der
   Architektur, da das Feld scheinbar innerhalb kürzester Zeit an die Maschine
   gefallen ist. Er spricht mit einer Energie mit Alessia, die sie von ihm
   überhaupt nicht kennt, und fordert sie auf, ihr Studium zu wechseln.

   Mit Luca scheint Giovanni unfairer weise versöhnlicher umzugehen. Dieser
   musste sich immer anhöhren was für einen exzellenten Weg seine Schwester
   eingeschlagen hatte, wo er nie hatte mithalten können. Doch unter der
   veränderten Situation scheint der Handwerkliche Beruf letzten Endes doch die
   bessere Wahl gewesen zu sein.

   Alessia kommt in eine innere Krise. Sie möchte sich sicherlich nicht gegen
   ihren Vater stellen, doch kommmt für sie auch nicht in Frage, ihren
   beruflichen Lebenstraum einfach so aufzugeben. In ihrem inneren Konflikt, der
   immer noch belastender zu werden scheint grenzt sie sich immer mehr von ihren
   Freunden ab.

   Die Wendung kommt für sie von einer sehr unerwarteten Seite. Es ist plötzlich
   Luca der mit  einer versöhnlichen Art ankommt. Er versteht ihre Not, und
   möchte sie unterstützen, auch wenn er konkret nicht genau weiss, wie das
   aussehen soll. Für Alessia ist dies zumindest eine Aufmunterung in sich und
   sie schöpft neue Kraft. Sie will nicht kampflos aufgeben.

   Alessia beginnt zu rebellieren. Im Unterricht, den sie weiterhin besucht,
   versucht sie nicht mehr integrative Wege zu fahren, sondern harte,
   Konfrontationsorientierte Spuren einzuschlagen.

   Tim scheint sichtlich verstört von Alessias neuer Art. Nach kurzer Zeit
   vertraut sie sich ihm an. Sie erzählt ihm vieles von ihrer Not, der Situation
   zu Hause, und ihren Ängsten, wenn sie in die Zukunft blickt. Sie erzählt ihm
   überdies auch Details über die Umstände in der Regierung, Wie weit Mira
   vorgedrungen ist, und wie es um die Architekten der Stadt und im Amt gestellt
   ist.

   Vor diesem Hintergrund beschliessen Alessia und Tim gemeinsam Widerstand zu
   leisten und eine Bewegung ins Leben zu rufen, die die K.I. eindämmen
   soll. Natürlich soll Jan auch mitmachen, denn er hat Zugang zu andern Kreisen
   junger Leute, wo Alessia und Tim weniger zugriff haben. Als sie Jan ihre
   Absichten erklären zeigt dieser den beiden schuldbewusst, dass er die ganze
   Zeit über Mira auf seinem Computer am laufen hatte.

** Episode 6 | Tim

*** Punkte in Geschichte

**** Ale wird wütend, Tim als Vermittler zwischen Jan und Ale

**** Versöhnung. Was könnte man tun? Alle wieder vereint

**** Gemeinsame Planung für Massnahmen gegen Mira

**** Anschläge

**** Niederlage der Studentenbewegung, Resignation

**** Tim vermag abermals alle zu motivieren

**** lange Krisensitzung

**** Mira Fail, Nur noch Baustelle in der Stadt

** Episode 7 | Professor Brändi
   
*** Punkte in Geschichte

**** Prof. Brändi versucht an ETH zu gelangen. Muss zu fuss kommen, da Infrastruktur erliegt.

**** Brändi und Studenten kommen zusammen.

**** Fünf Tage später haben sich die Leute an die gegebenheiten angepasst, ganz nach Brändis Vorbild zu fuss oder mit Velo
      
     Bild auf dem man sieht, wie die Menschen die Strassen zur Fussgängerzone
     gemacht haben.

**** Studenten gehen unter Führung von Brändi auf Baustelle, stoppen Materialzufuhr

**** Versuchen Brown zu finden, finden ihn

**** Studenten und Brändi versuchen Bronw auf ihre seite zu bringen

**** Brown willigt ein zu helfen

**** Mira upgrade

**** Mira keine Alleinmacht mehr

**** Anders Denken, Mira stoppen, aber nicht radikal vernichten

** Episode 8 | Gudzilla
   
*** Punkte in Geschichte

**** 
